### ISSUE TITLE
Async speech to text - cannot get result based on Job Id

### ISSUE THREAD

**Issue by KrzysztofZalasa** [googleapis/python-speech#11]
Google Cloud Speech to text API in beta version supports long_running_recognize method which returns FutureOperation. Then you may use result method on it in order to wait for finishing or there is an option to pass callback. Both approaches works fine in case, when processing and analysis is part of same file.

My customer is working on solution, when one microservice is responsible for sending audio file for recognition and second one is taking care about analysis of output. For now, in order to check current progress of job I may use following code:

`from google.cloud import speech_v1p1beta1 as speech

client = speech.SpeechClient()
response = client.transport._operations_client.get_operation('ID_OF_JOB')`

Unfortunately, response is not an object of proper class and developer needs to handle it on its side. I believe you we may just add method like

`client.get_long_running_recognize_result('ID_OF_JOB')` which may call https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/operations/get REST API. It will makes it easier to use and it seams to be low hanging fruit.

**Comment by vcidst** [comment]
Can you please add an example of this to the documentation? I'm trying to convert a batch of long audio files and it might take me a whole day with synchronous method

**Comment by vcidst** [comment]
In your [documentation](https://googleapis.dev/python/speech/latest/index.html#asynchronous-recognition), the link to `Speech Asynchronous Recognize` takes me to Google STT Release Notes. The method it refers to does not seem to exist in the REST API reference either.

**Comment by b-loved-dreamer** [comment]
I believe this answers the original question. Just noted that it retrieves the operation by operation name.

> For now, if you have the operation name:
> 
> ```
> operation = client.long_running_recognize(config, audio)
> name = operation.operation.name
> ```
> 
> you can do:
> 
> ```
> from google.api_core import operation as operation_core
> ...
> 
> client = speech.SpeechClient(credentials=credentials)
>  
> operation_instance = client.transport._operations_client.get_operation(name)
> operation_response = operation_core.from_gapic(
>     operation_instance,
>     client.transport._operations_client,
>     types.LongRunningRecognizeResponse,
>     metadata_type=types.LongRunningRecognizeMetadata,
> )
> if operation_response.done():
>     ...
> else:
>     ...
> ```

I will proceed to close this issue.

**Comment by rambho** [comment]
@b-loved-dreamer This is the same solution referenced in 2018, which does not work with latest google cloud speech clients.
`"AttributeError: 'SpeechClient' object has no attribute 'transport'"`
It's baffling that this is not documented somewhere.

**Comment by normand1** [comment]
Please document this. [The examples provided in the current docs are not actually asynchronous](https://cloud.google.com/speech-to-text/docs/samples/speech-transcribe-async).
This is the only way to call back using the returned operation name at a later time and it has apparently changed many times in the last few years. I'm sure people would appreciate this example being more prominently featured. I know I would have.
