### ISSUE TITLE
Feature Request : Exporting "*Response" Class to JSON.

### ISSUE THREAD

**Issue by seastar105** [googleapis/python-speech#111]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Google Speech API to make transcript of some audio files. 
It's uncomfortable to export recognition results with full information(Transcript, TimeStamp, Alternatives, WordInfo, Confidence).

 **Describe the solution you'd like**
I want Response classes(LongRunning~, Recognize~, Streaming~) to have features that export information to json.

 **Describe alternatives you've considered**
I wrote the code works well only with RecognizeResponse and using it now.

 **Additional context**

**Comment by b-loved-dreamer** [comment]
@seastar105 — Thank you for filing this issue. We are going to carefully consider this feature request for updates to the ```python-speech``` client.

**Comment by b-loved-dreamer** [comment]
Closing this issue. A PIT has been logged.

**Comment by seastar105** [comment]
Hi, @b-loved-dreamer .
I'm sorry for asking it. What does PIT mean?

Thanks.

**Comment by b-loved-dreamer** [comment]
@seastar105, Public Issue Tracker.

**Comment by seastar105** [comment]
Thank you I found it. 
"MessageToJson(response._pb)" works well.
