### ISSUE TITLE
Await rpc result in 'SpeechAsyncClient.streaming_recognize'

### ISSUE THREAD

**Issue by 0xfadeef** [googleapis/python-speech#114]
**Is your feature request related to a problem? Please describe.**
It is extremely confusing that method `streaming_recognize` in `SpeechAsyncClient` class doesn't await on `response` and returns coroutine object instead of async iterator. Besides that returning a coroutine is AFAIK a quite unusual practice, it also contradicts to what [documentation](https://googleapis.dev/python/speech/latest/speech_v1/services.html#google.cloud.speech_v1.services.speech.SpeechAsyncClient) says.

The other two methods in `SpeechAsyncClient` class (`recognize` and `long_running_recognize`) await for the rpc to complete and return the result, which is natural and expected behaviour. Method `streaming_recognize` in `SpeechClient` class returns iterator. I see no reason why its asynchronous counterpart should behave differently.

 **Describe the solution you'd like**
Declare `streaming_recognize` method as a coroutine. Then, `await` on `rpc(...)` to obtain the response in the form of async iterator. Finally, `return response`.

**Comment by b-loved-dreamer** [comment]
Hi @0xfadeef — Thank you for posting your concern about the ```SpeechAsyncClient```. Unfortunately, at this time, we don’t have a sample on the ```SpeechAsyncClient```.  This client will be included in the next meeting for possible sample and documentation development. For now, you would have t rely on generated ```refdocs``` and any prior knowledge about async.

**Comment by 0xfadeef** [comment]
Hello @b-loved-dreamer! Let me clarify: this issue is not about missing samples or documentation. The `streaming_recognize` method of `SpeechAsyncClient` class should be a coroutine function, but for some reason it's not (frankly speaking, I think someone just forgot to put `async`/`await` in this method, that's all). Although it doesn't break anything, this leads to inconvenient and inconsistent API.

**Comment by b-loved-dreamer** [comment]
@0xfadeef — thank you for noticing and documenting this situation. I will notify the relevant parties about your discovery and await for any feedback from the team.

**Comment by b-loved-dreamer** [comment]
Closing this issue. The relevant party has been notify about this situation and are taking care of it.

**Comment by 0xfadeef** [comment]
@b-loved-dreamer Hi! It's been almost a year and the issue still remains. Could you please comment whether it's gonna be fixed or not? Thanks.
