### ISSUE TITLE
Cant run Demo software

### ISSUE THREAD

**Issue by joevirden2** [googleapis/python-speech#118]
First time user.  I cant get the quickstart python code to run.  I keep getting the following error from line 14

"AttributeError: 'Module' object has no attribute "RecognitionAudio'

what might be causing this? 

-Joe Virden

**Comment by lucaswadedavis** [comment]
Hi there! Can you share a little more information? A snippet of code to see what you're doing and more complete stack trace would be helpful.

**Comment by Dorteel** [comment]
I have the same problem by just running the code below, using Python 2.7.17 on Windows
installed it with ```pip install --upgrade google-cloud-speech```
```
from google.cloud import speech
import os

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'path-to-credential.json'

client = speech.SpeechClient()

gcs_uri = "gs://cloud-samples-data/speech/brooklyn_bridge.raw"

audio = speech.RecognitionAudio(uri=gcs_uri)

config = speech.RecognitionConfig(
    encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
    sample_rate_hertz=16000,
    language_code="en-US",
)

esponse = client.recognize(config=config, audio=audio)

for result in response.results:
    print("Transcript: {}".format(result.alternatives[0].transcript))
```

**Comment by lucaswadedavis** [comment]
I'm having a hard time replicating the issue. Maybe related: towards the end of your code sample you have

```esponse = client.recognize(config=config, audio=audio)```

where maybe you mean

```response = client.recognize(config=config, audio=audio)```
