### ISSUE TITLE
Punctuation with transcribe_streaming_mic

### ISSUE THREAD

**Issue by Slartibart-fast** [googleapis/python-speech#123]
Is it possible to enable punctuation with the transcribe_streaming_mic code? I tried setting enable_automatic_punctuation=True in the RecognitionConfig, but it had no effect.

**Comment by b-loved-dreamer** [comment]
Hi @Slartibart-fast — thank you for using our service. According to our documentation:

> To enable automatic punctuation, set the enableAutomaticPunctuation field to true in the RecognitionConfig parameters for the request. The Speech-to-Text API supports automatic punctuation for all speech recognition methods: speech:recognize, speech:longrunningrecognize, and Streaming. Please [read](https://cloud.google.com/speech-to-text/docs/automatic-punctuation#:~:text=To%20enable%20automatic%20punctuation%2C%20set,speech%3Alongrunningrecognize%20%2C%20and%20Streaming.).

Are you adding the ```enable_automatic_punctuation``` in the right config? The ```StreamingRecognitionConfig``` takes in a ```RecognitionConfig``` which is where you should place your ```enable_automatic_punctuation``` field.

**Comment by Slartibart-fast** [comment]
Hi @b-loved-dreamer! Thank you for your response. It does work now without me changing anything. Maybe it just took some time or the original config was cached. 

I'm closing the issue :)
