### ISSUE TITLE
Slightly wrong word time offsets after upgrading to v2.1.0

### ISSUE THREAD

**Issue by nirb999** [googleapis/python-speech#124]
After upgrading Speech from v1.3.2 to v.2.1.0, word time offsets are slightly wrong when doing infinite streaming transcribing.
The first request iteration is identical in both versions. After the first request restart, an offset of ~200msec is created between the versions, accumulating for each new iteration.

After investigation, the root cause is a code introduced (stream pre-fetch) in google-api-core v1.17.0: 
https://www.github.com/googleapis/python-api-core/commit/2b103b60ece16a1e1bc98cfda7ec375191a90f75

This was later wrapped with the flag _prefetch_first_result_:
https://github.com/googleapis/python-api-core/commit/74e0b0f8387207933c120af15b2bb5d175dd8f84#diff-9aeb5107dac746ab0e51a30c001ca48df095ca511bc881c40ed0c5e71cf7dc73

It seems that Speech is also better with the prefetch disabled, so _prefetch_first_result_  should be set to False for streaming_recognize.
File:  google/cloud/speech_v1/services/speech/client.py

```
def streaming_recognize(
        self,
        requests: Iterator[cloud_speech.StreamingRecognizeRequest] = None,
        *,
        retry: retries.Retry = gapic_v1.method.DEFAULT,
        timeout: float = None,
        metadata: Sequence[Tuple[str, str]] = (),
    ) -> Iterable[cloud_speech.StreamingRecognizeResponse]:

        self._transport.streaming_recognize._prefetch_first_result_ = False

        # Wrap the RPC method; this adds retry and timeout information,
        # and friendly error handling.
        rpc = self._transport._wrapped_methods[self._transport.streaming_recognize]

        # Send the request.
        response = rpc(requests, retry=retry, timeout=timeout, metadata=metadata,)

        # Done; return the response.
        return response
```

**Comment by b-loved-dreamer** [comment]
Hi @nirb999 — thank you taking note of this. We will investigate this further.

**Comment by nirb999** [comment]
Thanks @b-loved-dreamer .
Let me know if you need my results or test code.

**Comment by b-loved-dreamer** [comment]
Hi @nirb999 — I was not able to repro this issue. Please share a snippet of your code.

**Comment by nirb999** [comment]
Hi @b-loved-dreamer ,
Please take a look here: https://github.com/nirb999/transcribe_streaming_infinite
All the info is there.

**Comment by b-loved-dreamer** [comment]
I am unable to replicate he described behavior locally. Are you able to confirm that your local environment is adequate?
