### ISSUE TITLE
Getting started guide for Raspberry Pi  fails - 'module' object has no attribute 'RecognitionAudio'

### ISSUE THREAD

**Issue by wighthat** [googleapis/python-speech#148]
#### Environment details

  - OS type and version: Rasberry Pi 4, OS  Raspbian GNU/Linux 10 (buster)
  - Python version: Python 3.7.3
  - pip version: pip 21.0.1
  - `google-cloud-speech` version: google-cloud-speech Version: 2.3.0

#### Steps to reproduce

  1. Follow Google Cloud Text to speech getting started guide at https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries. Follow Python branch as below:
  2. pip install --upgrade google-cloud-speech
  3. try to run below code from the docs

#### Code example

```python

# Imports the Google Cloud client library
from google.cloud import speech


# Instantiates a client
client = speech.SpeechClient()

# The name of the audio file to transcribe
gcs_uri = "gs://cloud-samples-data/speech/brooklyn_bridge.raw"

audio = speech.RecognitionAudio(uri=gcs_uri)

config = speech.RecognitionConfig(
    encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
    sample_rate_hertz=16000,
    language_code="en-US",
)

# Detects speech in the audio file
response = client.recognize(config=config, audio=audio)

for result in response.results:
    print("Transcript: {}".format(result.alternatives[0].transcript))
```

#### Stack trace
```
Traceback (most recent call last):
  File "google_speech.py", line 11, in <module>
    audio = speech.RecognitionAudio(uri=gcs_uri)
AttributeError: 'module' object has no attribute 'RecognitionAudio'

```

Thanks

**Comment by b-loved-dreamer** [comment]
Hi @wighthat — I was able to run the code sample without any issues. You can try uninstalling ```google-cloud-speech``` and reinstalling it bak on. Let me know if this helps.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We replied to this thread a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue.
