### ISSUE TITLE
Speech to Text API is slow

### ISSUE THREAD

**Issue by BoPengGit** [googleapis/python-speech#150]
Hi,

I'm using the guide on ["Transcribing long audio files using a Google Cloud Storage file" here.](https://cloud.google.com/speech-to-text/docs/async-recognize) 

But the speed is slow when using the "enhanced video" model with "enable_automatic_punctuation". It takes around 2.5 minutes per 10 minutes of audio duration.

Here is my config:

    config = speech.RecognitionConfig(
      encoding=speech.RecognitionConfig.AudioEncoding.FLAC,
      audio_channel_count=2,
      language_code="en-US",
      use_enhanced=True,  # Use enhanced model.
      model='video',  # Enhanced model for videos
      enable_word_time_offsets=True,  # Add the word video times (seconds)
      enable_automatic_punctuation=True  # Add punctuation to the transcript.
    )
    operation = client.long_running_recognize(config=config, audio=audio)

Is there any way we can get a response that is faster. Does it really take this long for the speech recognition model + the NLP punctuation model ~2 minutes for a 10 minute duration audio file?

Thank you so much for your help.

**Comment by b-loved-dreamer** [comment]
Hi @BoPengGit — are you performing any audio processing/conversion before sending your requests with the client? Please provide as much context as you can.

**Comment by BoPengGit** [comment]
Hi Franklin,

Good to meet you. Yes I first convert the audio file to FLAC. 

audio_file = AudioSegment.from_file('audio_file.mp3', 'mp3'). # Load audio file
audio_file.export("audio_file.flac" ,format = "flac"). # Convert audio file to FLAC and save the file. 

audio = speech.RecognitionAudio(uri=gcs_uri)
    
config = speech.RecognitionConfig(
    encoding=speech.RecognitionConfig.AudioEncoding.FLAC,
    audio_channel_count=2,
    language_code="en-US",
    use_enhanced=True,  # Use enhanced model.
    model='video',  # Enhanced model for videos
    enable_word_time_offsets=True,  # Add the word video times (seconds)
    enable_automatic_punctuation=True  # Add punctuation to the transcript.
)

operation = client.long_running_recognize(config=config, audio=audio)

**Comment by b-loved-dreamer** [comment]
Thank you. Are you weighing the impact of such conversion on your converted files? 
We recommend this [tool](https://cloud.google.com/solutions/media-entertainment/optimizing-audio-files-for-speech-to-text) for file conversion. Also, please check the details of your files both before and after conversion using this other [tool](http://sox.sourceforge.net/).

Using sox:

<img width="500" alt="Screen Shot 2020-09-16 at 10 43 04 AM" src="https://user-images.githubusercontent.com/69214580/117050300-09a34b80-acca-11eb-83cf-96645ed817a8.png">

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked provided a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue.
