### ISSUE TITLE
Support output_config in long_running_recognize

### ISSUE THREAD

**Issue by ffeldhaus** [googleapis/python-speech#169]
There is basic support for `output_config` by using the built in type `LongRunningRecognizeRequest` but it is not possible to use `client.long_running_recognize` and pass the `output_config`.

This works
```
from google.cloud import speech_v1p1beta1 as speech
client = speech.SpeechClient()

gcs_uri = "gs://example-bucket/test.wav"
audio = speech.RecognitionAudio(uri=gcs_uri)

config = speech.RecognitionConfig(language_code="en-US")

output_audio_config = speech.TranscriptOutputConfig(gcs_uri="gs://example-bucket/test.txt")

long_running_recognize_request = speech.types.LongRunningRecognizeRequest(audio=audio, config=config, output_config=output_audio_config)

response = client.long_running_recognize(long_running_recognize_request)
```

The following should work, but does not work

```
from google.cloud import speech_v1p1beta1 as speech
client = speech.SpeechClient()

gcs_uri = "gs://example-bucket/test.wav"
audio = speech.RecognitionAudio(uri=gcs_uri)

config = speech.RecognitionConfig(language_code="en-US")

output_audio_config = speech.TranscriptOutputConfig(gcs_uri="gs://example-bucket/test.txt")

response = client.long_running_recognize(audio=audio, config=config, output_config=output_audio_config)
```

**Comment by munkhuushmgl** [comment]
Which version of `google-cloud-speech`  r u using?


By just peeking at it, i think you can only pass `output_audio_config` to LongRunningRecognizeRequest

Please refer to the following code:
https://github.com/googleapis/python-speech/blob/e3a6748dc836e530d0eb802d149fd6d99b492150/google/cloud/speech_v1p1beta1/services/speech/client.py#L453-L462

**Comment by ffeldhaus** [comment]
I am using the latest 2.4.0 version. I created this feature request to ask to add support for `output_audio_config` in `long_running_recognize()`.

**Comment by munkhuushmgl** [comment]
@ffeldhaus what's your reasoning for this feature request?

**Comment by b-loved-dreamer** [comment]
Hi @ffeldhaus — as mentioned by @munkhuushmgl, you should pass the ```output_audio_config``` to the ```LongRunningRecognizeRequest```.

Please take a look:

https://github.com/googleapis/python-speech/blob/master/samples/snippets/speech_to_storage_beta.py

// ---------------------------------------------------------
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue if needed.

**Comment by fblascogarma** [comment]
Hi there, I'm having the same issue. I'm getting:

> TypeError: long_running_recognize() got an unexpected keyword argument 'output_config'

I'm using google-cloud-speech v 2.16.2.

This is the operation request in Python:
`
operation = client.long_running_recognize(
    config=config, 
    audio=audio,
    output_config=transcript_output_config
    )
`

When I remove 'output_config', the request is processed successfully. 

Please help.

Thanks!

**Comment by cherba** [comment]
@b-loved-dreamer, @munkhuushmgl 

I think request is to have a consistent interface to speech client, in particular this method

https://github.com/googleapis/python-speech/blob/39b0a2cc2f0735cf02fc02982827f4a8c7aada0b/google/cloud/speech_v1/services/speech/client.py#L571

takes in top level request or flattened parameters. Because `output_config` was added tolater to the `LongRunningRecognizeRequest`, it seems it has not been added as an option as a flattened parameter.

While a minor issue, since users can construct `LongRunningRecognizeRequest` instead, Google Cloud Speech-to-text documentation https://cloud.google.com/speech-to-text/docs/async-recognize#speech_transcribe_async_gcs-python
shows flattened syntax, which could lead to confused users on how to specify `output_config` in that case.

**Comment by fblascogarma** [comment]
Thank you, @cherba ! You instructions were gold.

I was able to solve the issue by first constructing the LongRunningRecognizeRequest and then pass it to client.long_running_recognize(request=request).

See code below

`
request = speech.LongRunningRecognizeRequest(
    config=config, 
    audio=audio,
    output_config=transcript_output_config
)

operation = client.long_running_recognize(
    request=request
    )
`

**Comment by saramsbodo** [comment]
> Thank you, @cherba ! You instructions were gold.
> 
> I was able to solve the issue by first constructing the LongRunningRecognizeRequest and then pass it to client.long_running_recognize(request=request).
> 
> See code below
> 
> ` request = speech.LongRunningRecognizeRequest( config=config, audio=audio, output_config=transcript_output_config )
> 
> operation = client.long_running_recognize( request=request ) `

**Declare LongRunningRecognizeRequest outside worked for me either!!**
