### ISSUE TITLE
400 Inline audio exceeds duration limit

### ISSUE THREAD

**Issue by Raamyy** [googleapis/python-speech#18]
I am running speech to text with python and I have audio files larger than 60 seconds, I get the following error:
```google.api_core.exceptions.InvalidArgument: 400 Inline audio exceeds duration limit. Please use a GCS URI.```

I understand that it exceeds the 60 seconds duration quota for the files to be read directly from the file system.

**I need to know how to upload the file to GSC and get back it's URI using Python.**

**Comment by luigiam** [comment]
Just to clarify: when an audio file is longer than 1 minute, you can only run asychronous speech recognition if the audio file is uploaded to GSC (i.e. not locally). Is this correct?

**Comment by luigiam** [comment]
Just to clarify: when an audio file is longer than 1 minute, you can only run asychronous speech recognition if the audio file is uploaded to GSC (i.e. not locally). Is this correct?

**Comment by Raamyy** [comment]
@luigiam Yes you will need to upload it to a storage bucket to be able to process it.

**Comment by kylefoley76** [comment]
@Rammyy are you sure about this?  It says very clearly in the google documentation that you can convert long audio local files right here:
https://cloud.google.com/speech-to-text/docs/async-recognize
These samples use a local file to store the raw audio input for the long-running transcription process.

This seems to be a very unnecessary step to me.

**Comment by Raamyy** [comment]
@kylefoley76 Thank you for letting me know.

I Think that when I didn't see the example for uploading it from local file or it has been recently added.

I implemented it in my system as the tutorial and it worked great !

It preserves so much upload time overhead and space in the GSC storage.

Thanks again for letting me know.

**Comment by Raamyy** [comment]
Currently I am getting a `504 deadline error` I think it is caused by the network for some reason that can't upload the audio file content in certain time interval.

There were some settings in uploading to google storage where I set chunk sizes for the file. So it is uploaded as chunks not as a whole, which helps preventing this error with slow internet speeds.

**Comment by kylefoley76** [comment]
Have you been able to get it to work with large files in a local folder?   I'm getting the 400 error.  Then again I remember that I used to have a similar problem with google api when I had a slow upload speed.  So let me see what happens when I get home and have a faster connection.

**Comment by rafael-ferro** [comment]
Did you manage to get it working? I'm also getting the 400 error with local audio files longer than 1 minute. I don't understand what's wrong, since I just followed the example from the [documentation](https://cloud.google.com/speech-to-text/docs/async-recognize). On the other hand, it works if I provide the URI for the file in a bucket.

**Comment by Raamyy** [comment]
@rafael-ferro No I am working with the google bucket storage solution.
