### ISSUE TITLE
how to enable `Data Logging opt-in` when doing api request?

### ISSUE THREAD

**Issue by Cedric-Chen** [googleapis/python-speech#186]
The price for api calls is cheaper with data Logging opt-in. 

I don't know the default for this option when using google speech api. If not, how to enable this option? Thanks!

Below are my sample codes.
```Python
    audio = speech.RecognitionAudio(content=content)
    config = speech.RecognitionConfig(
        encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=8000,
        language_code="en-US",
        # Enable automatic punctuation
        enable_automatic_punctuation=True,
    )

    response = client.recognize(config=config, audio=audio)
```

**Comment by b-loved-dreamer** [comment]
Hi @Cedric-Chen — thank you for filling this issue. This [documentation](https://cloud.google.com/speech-to-text/docs/enable-data-logging) page includes steps to enable [data logging](https://cloud.google.com/speech-to-text/docs/data-logging) for Speech-to-Text on a Google Cloud project.

**Comment by Cedric-Chen** [comment]
> Hi @Cedric-Chen — thank you for filling this issue. This [documentation](https://cloud.google.com/speech-to-text/docs/enable-data-logging) page includes steps to enable [data logging](https://cloud.google.com/speech-to-text/docs/data-logging) for Speech-to-Text on a Google Cloud project.

Hi, @b-loved-dreamer ! The problem is solved. Thank you a lot!
