### ISSUE TITLE
Receiving AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by MadelineGrimes** [googleapis/python-speech#195]
I have implemented the code provided while adding only my bucket name at the bottom: 

`    if args.path.startswith("gs://bucket_name"):
        transcribe_model_selection_gcs(args.path, args.model)
    else:
        transcribe_model_selection(args.path, args.model)`

When running the program, I receive the error: 

`Traceback (most recent call last):
  File "speech-to-text.py", line 81, in <module>
    if args.path.startswith("gs://bucket_name"):
AttributeError: 'NoneType' object has no attribute 'startswith'`

What am I missing? Thank you!

**Comment by b-loved-dreamer** [comment]
Hi @MadelineGrimes — thank you for posting your concern. It looks like your code is calling a function that does not exist, but its unclear what the logic is here. I need more context. Can you please share a snippet of your code? I will be able to help then.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
