### ISSUE TITLE
Unstable Speech Diarization Results

### ISSUE THREAD

**Issue by jpolin** [googleapis/python-speech#20]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-speech/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-python
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 18
  - Python version: `python --version`3.7
  - pip version: `pip --version` 20.0.2
  - `google-cloud-speech` version: `pip show google-cloud-speech` Version: 1.3.2

#### Steps to reproduce

I set up a server that reads audio streamed from ffmpeg, and attempts to label the speaker for every word. The results have pretty poor accuracy, and seem to change drastically in successive calls. The results feel at best unstable, at worst random. I'm wondering if there might be something else I'm missing/doing sub-optimally.

I'm not sure of the best way to "reproduce" in a way that others could as well (if you have guidance there, happy to put something together). 

#### Code example

Here are the relevant code snippets pulled out of the server:
```python
config = dict(
    encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
    language_code='en-US',
    sample_rate_hertz=16000,
    enable_speaker_diarization=True,
    diarization_speaker_count=2
)
args = dict(config=config,
            single_utterance=False,
            interim_results=False)
streaming_config = types.StreamingRecognitionConfig(**args)
...
client = speech.SpeechClient()
args = dict(timeout=1000)
return client.streaming_recognize(self.streaming_config_,
                                          self._requests(), **args)
```

Streaming microphone->webserver:

```bash
ffmpeg -f avfoundation -i ":0"  -ac 1 -f s16le -ar 16000 udp://$HOST:13580
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by munkhuushmgl** [comment]
@jpolin Could you share your code snippet of import section?
For example:
```
from google.cloud import speech_v1p1beta1
```

**Comment by munkhuushmgl** [comment]
Have you tried with async (LRO) and sync to see if you can get the different results?

**Comment by munkhuushmgl** [comment]
It has been reported to backend team to try and get this fixed. 

Meanwhile, here is a big list of recommendations you can take a look
https://cloud.google.com/speech-to-text/docs/best-practices

**Comment by munkhuushmgl** [comment]
I have heard back from the team and they are aware of the issue but we don't have a timeline for a fix.

For some use cases, diarization can lead to inconsistent results (different runs for the same audio results in different diarazation results). 

Suggestion:
`
Different formats could help getting more stable diarization results in some cases and audios (for example, FLAC seems to give better results overall). I would suggest to test different models and formats and see what works best.
`

Feel free to reach out or reopen this issue.

**Comment by plizeeee** [comment]
Hi, was just wondering if this issue has been worked on since it has been some time since the last update. Running diarization with the same audio data still seems to give different results.

**Comment by platramos** [comment]
I'm also still having the same issue and have tried various models and file types. Has anyone found a way to consistently improve accuracy or has this issue been addressed on the backend?
