### ISSUE TITLE
400 Audio Timeout Error: Long duration elapsed without audio. Audio should be sent close to real time

### ISSUE THREAD

**Issue by nguyedinhduc** [googleapis/python-speech#209]
i run script i run script transcribe_streaming_infinite.py , I forgot it for 30 minutes and got this error
![Brush-#2](https://user-images.githubusercontent.com/46533588/125312253-50fb2780-e35e-11eb-8df0-e871b0443b52.png)

**Comment by busunkim96** [comment]
Hi,

It looks like the API expects audio to be continually sent when using the streaming method. If you don't need real time transcription, you can use one of the other methods.

See "Transcribing long audio files" and "Transcribing short audio files" on https://cloud.google.com/speech-to-text/docs/how-to.

**Comment by nguyedinhduc** [comment]
> Hi,
> 
> It looks like the API expects audio to be continually sent when using the streaming method. If you don't need real time transcription, you can use one of the other methods.
> 
> See "Transcribing long audio files" and "Transcribing short audio files" on https://cloud.google.com/speech-to-text/docs/how-to.

i want it to always listen because i can speak any time , is there any way to do it ?

**Comment by busunkim96** [comment]
Hmm, I'm not sure about that. @telpirion @sirtorry Could you take a look at this question?

**Comment by b-loved-dreamer** [comment]
Hi @nguyedinhduc - you can try to add an additional parameter ```timeout``` to the recognizer like so:

``` 
           responses = client.streaming_recognize(
                requests=requests, config=streaming_config, timeout=3600
            )
```

Let us know if this helps.

**Comment by nguyedinhduc** [comment]
> Hi @nguyedinhduc - you can try to add an additional parameter `timeout` to the recognizer, like so:
> 
> ```
>            responses = client.streaming_recognize(
>                 requests=requests, config=streaming_config, timeout=3600
>             )
> ```
> 
> Let us know if this helps.

i'm trying it, but it error after 90 minutes

**Comment by nguyedinhduc** [comment]
after adding timeout ,i tried a lot of .  as a result it works for a long time then it error

**Comment by nguyedinhduc** [comment]
> Hi @nguyedinhduc - you can try to add an additional parameter `timeout` to the recognizer, like so:
> 
> ```
>            responses = client.streaming_recognize(
>                 requests=requests, config=streaming_config, timeout=3600
>             )
> ```
> 
> Let us know if this helps.

timeout option  didn't work, i tried a lot

**Comment by b-loved-dreamer** [comment]
Hey @nguyedinhduc. What values are you using to override timeout?

**Comment by nguyedinhduc** [comment]
> Hey @nguyedinhduc. What values are you using to override timeout?

timeout value is 3600

**Comment by b-loved-dreamer** [comment]
I've found these resource:
https://google-cloud-python.readthedocs.io/en/stable/speech/gapic/api.html
https://gax-python.readthedocs.io/en/latest/generated/google.gax.html#google.gax.CallOptions

**Comment by b-loved-dreamer** [comment]
Hi @nguyedinhduc. The streaming recognizer is designed to receive audio in real time. 

Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it.
