### ISSUE TITLE
I want to know how to use api key

### ISSUE THREAD

**Issue by liming-developer-python** [googleapis/python-speech#234]
I am new at google cloud speech-to-text service.
I got api key but don't know how to use it.
Please give me a little help.
I want to use it on python flask web application. According to guide, it said that I should import key from environment json file but I am not sure how to create json file and how to use it.

**Comment by b-loved-dreamer** [comment]
Hi @liming-developer-python — thank for you posting your concern. You can review this [portal](https://cloud.google.com/speech-to-text/docs/before-you-begin) to learn the steps to get you started using our clients.

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We provided feedback a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
