### ISSUE TITLE
500 Exception deserializing response!

### ISSUE THREAD

**Issue by luxenduf** [googleapis/python-speech#238]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

#### Description

We are using the google-cloud-speech library to validate streaming Speech-to-Text API based on the public document, but we got a 500 error occasionally (please see Stack trace section).

##### Questions

1. What is the root cause of this 500 error?
2. How to prevent this issue?
3. Why is it not possible to reproduce the same error even using the same data? / Is it possible to reproduce it?

#### Environment details

  - OS type and version: N/A
  - Python version: 3.6.8
  - pip version: N/A
  - `google-cloud-speech` version: 2.4.0

#### Steps to reproduce

This error could not be reproduced even with the same streaming audio data we dumped.

#### Code example

Implemented code by referring to this public doc [1].
And here is a StreamingRecognitionConfig:

```python
        config = speech.RecognitionConfig(
            encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
            sample_rate_hertz=8000,
            language_code='ja-JP',
            enable_automatic_punctuation=True,
            profanity_filter=True,
            speech_contexts=[speech.SpeechContext(
                phrases=phrases
            )])
        streaming_config = speech.StreamingRecognitionConfig(
            config=config,
            single_utterance=False,
            interim_results=True)
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 107, in next
    return six.next(self._wrapped)
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib64/python3.6/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception deserializing response!"
        debug_error_string = "None"
>
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "udp_server.py", line 212, in listen_save_loop
    for response in responses:
  File "/usr/local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 110, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InternalServerError: 500 Exception deserializing response!

```

[1] https://cloud.google.com/speech-to-text/docs/streaming-recognize#performing_streaming_speech_recognition_on_an_audio_stream

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.

**Comment by kei982** [comment]
I use the speech-to-text api almost as it is.

It receives the UDP packet (RTP data) from another server and uses the VAD library to pass a voice packet with silence eliminated to the speech-to-text API.

**Comment by luxenduf** [comment]
Hello @b-loved-dreamer ,

Thank you for your quick response.
Sorry, it seems not to be able to re-open this issue from my side. 
Could you please re-open this issue, check the kei982's answer and ask him about details directly hereafter?
