### ISSUE TITLE
speaker_tag for interim results OR trigger final response when speaker changes

### ISSUE THREAD

**Issue by jpolin** [googleapis/python-speech#32]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

I'm looking to build a real-time application that includes speaker diarization. Waiting for the full responses (which include the transcript and `speaker_tag`) takes at least 10 seconds, on average. I want to be able to detect change in speaker in near-real time O(1 second).

 **Describe the solution you'd like**

Any of the following would work for me (in order of preference):

- Interim results include speaker_tag (guess)
- A "final result" is kicked back every time the speaker tag changes. Then, I can assume the previous speaker is still talking until I see a final response.

 **Describe alternatives you've considered**

I've tried figuring out a way to "flush" more often so that I can see responses every O(1 second), but no luck. Maybe I'm missing something else?

 **Additional context**

Nothing I can think of, but happy to answer any questions :) Thanks team!

**Comment by munkhuushmgl** [comment]
I just added to my hotlist, and I will look into it this week.

**Comment by jpolin** [comment]
Great, thank you Mike!

**Comment by alex89607** [comment]
Interim results(include speaker_tag) that is interesting question and for me. Thanks team!

**Comment by munkhuushmgl** [comment]
@jpolin Could you share a code snippet where you using this feature?

**Comment by jpolin** [comment]
Hey Mike, I have some code set up for running the normal flow and using those speaker tags. I'm not sure if it would work for the interim results too—hard to test without having "the thing" in front of me :)

Do you just need a snippet for reading the result? If so I can clean that up and share.

**Comment by b-loved-dreamer** [comment]
Hi jpolin

As per the solution you'd like:

- No. You only get speaker_tags for the final responses. 

Can you please share the code snippet showing your RecognitionConfig & StreamingRecognitionConfig objects, also the request. Please keep in mind that speaker_tags are only included at the word level, and as a result, only for final responses.

**Comment by b-loved-dreamer** [comment]
Won't fix (No repro)

**Comment by b-loved-dreamer** [comment]
Won't fix (No repro)
