### ISSUE TITLE
Automate tests for STT on prem

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-speech#324]
STT on prem snippets were added on https://github.com/GoogleCloudPlatform/python-docs-samples/pull/4223 without automated tests. Being internally tracked on b/161897398. After some discussion we should add a mock unit test first and then follow up with a more integrated test when there is resource to do so.

**Comment by meredithslota** [comment]
Closing this issue here since it's tracked internally and the samples have fully migrated to python-docs-samples (I can't transfer issues between orgs, unfortunately).
