### ISSUE TITLE
is_final takes too long to get when the source language is pt-BR

### ISSUE THREAD

**Issue by Bigous** [googleapis/python-speech#367]
https://github.com/googleapis/python-speech/blob/9fc20917ce55106821963213f939c5cac46bba73/samples/microphone/transcribe_streaming_infinite.py#L248

Test the script with english and than switch to portuguese, just modifying the selected line to `pt-BR`... is there a way to get better results?
![example](https://user-images.githubusercontent.com/6886560/166121648-aee431bc-778e-4b5d-8a98-8b23f4973add.gif)

Here is how long it takes to me to receive it im pt-BR and in en-US.

**Comment by yil532** [comment]
According to here: https://cloud.google.com/speech-to-text/docs/languages, pt-BR is properly supported. There is no other way to make it faster as I know of.
