### ISSUE TITLE
Azerbaijani voice database on gTTS?

### ISSUE THREAD

**Issue by eminmammadov** [googleapis/python-speech#40]
As far as I know, there is no Azerbaijani voice database on gTTS. So how can we create the Azerbaijani voice database?
What are the first steps in this regard?

**Comment by munkhuushmgl** [comment]
@eminmammadov I asked from internal teams and found out it will take at least enterprise level database to get started on this process. How much voice data do you have in your database or your company's database?

**Comment by eminmammadov** [comment]
> @eminmammadov I asked from internal teams and found out it will take at least enterprise level database to get started on this process. How much voice data do you have in your database or your company's database?

there is no audio data, I want to create the audio data myself,

**Comment by telpirion** [comment]
Hello @eminmammadov: this is the repo for the Speech-to-Text Python client library. It is intended for usage in converting audio data to text. 

I think that you are looking for [Cloud Text-to-Speech](https://cloud.google.com/text-to-speech/docs), the service that generates audio data. You can see the supported languages in Text-to-Speech on [this page](https://cloud.google.com/text-to-speech/docs/voices).

**Comment by eminmammadov** [comment]
@telpirion Yes I was looking for it, thank you dear.

**Comment by Intizam1993** [comment]
@munkhuushmgl  Can you reach me on telegram? Intizam_mirzaevi
