### ISSUE TITLE
Documentation is outdated for "enable_word_time_offsets=True"

### ISSUE THREAD

**Issue by firozzer** [googleapis/python-speech#445]
Line no 44 in this file: https://github.com/googleapis/python-speech/blob/HEAD/samples/snippets/transcribe_word_time_offsets.py

It should be `enable_word_time_offsets=1`

And on another Google documentation page it shows camelCase format! https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig

**Comment by atulep** [comment]
Duplicate of: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9639
