### ISSUE TITLE
Speech to text: Max characters per line

### ISSUE THREAD

**Issue by yogeshdecodes** [googleapis/python-speech#463]
I want to limit the number of characters per sentence. By default, sentences are long and not useful for subtitle usecase.
I found on documentation that we can pass `Max characters per line` but not able to find exact attribute name for the same 
on python-speech.

<img width="873" alt="Screen Shot 2022-10-21 at 6 38 47 PM" src="https://user-images.githubusercontent.com/25588560/197203270-cfa2ce03-bede-4d0d-bb59-e0931414f64a.png">
Refer - https://cloud.google.com/community/tutorials/speech2srt

**Comment by atulep** [comment]
Hi @yogeshdecodes, Speech API doesn't support this functionality, so the client library also doesn't support it. The tutorial you were referring to introduced a utility function for this - https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/speech2srt/speech2srt.py#L57-L86. Closing this down, but please feel free to reach out again if you need more guidance here.
