### ISSUE TITLE
stt v2 BatchRecognizeRequest needs RecognitionOutputConfig

### ISSUE THREAD

**Issue by hinaloe** [googleapis/python-speech#508]
#### Environment details

  - OS type and version: `Linux 5.15.90.1-microsoft-standard-WSL2`
  - Python version: `Python 3.10.9`
  - pip version: `23.0.1`
  - `google-cloud-speech` version: `2.18.0`

#### Steps to reproduce

  1. Try sending Batch recognize (https://cloud.google.com/speech-to-text/v2/docs/batch-recognize)

#### Code example

```python
request=cloud_speech.BatchRecognizeRequest(
    recognizer=recognizer.name,
    config=config,
    files=[cloud_speech.BatchRecognizeFileMetadata(uri=gs_uri)],
#    recognitionOutputConfig=cloud_speech.GcsOutputConfig(uri=f"gs://{bucketName}/output/")
)
```

That makes 

> 400 Recognition output configuration must be specified.

and it appears that `recognitionOutputConfig` is not implemented.

**Comment by dizcology** [comment]
Hello @hinaloe :  The field `recognition_output_config` (note the snake case) is in the library: https://github.com/googleapis/python-speech/blob/main/google/cloud/speech_v2/types/cloud_speech.py#L1676
