### ISSUE TITLE
Enhanced model vs data logging

### ISSUE THREAD

**Issue by tekkkon** [googleapis/python-speech#51]
Hi,
Based on the [comment in the sample](https://github.com/googleapis/python-speech/blob/4214630c3318e6c9bc0a5156e20344956faf7d52/samples/v1/speech_transcribe_enhanced_model.py#L47). Seems to use the enhanced model, you have to opt in data logging. 
![image](https://user-images.githubusercontent.com/6827543/91908632-bcfe0100-ec60-11ea-9140-7896413a52e4.png)

But in this e[nhanced model description ](https://cloud.google.com/speech-to-text/docs/phone-model)page, looks like to use the enhanced model, you just need to set **useEnhanced=True** in the client request. Data logging is optional for lowering the cost of enhanced model.
![image](https://user-images.githubusercontent.com/6827543/91908429-64c6ff00-ec60-11ea-9585-ecd4aa3f7598.png)

Looks like there is a discrepancy between the sample code and feature descriptions? Please confirm whether the enhanced model is decoupled from data logging?

Thanks

**Comment by tekkkon** [comment]
Any updates on this?

**Comment by b-loved-dreamer** [comment]
Hi @tekkkon,

Based on the documentation:

> Google creates and improves enhanced models based upon data collected through data logging. If you opt-in to data logging, you can help Google improve these models and also enjoy a discount on your usage.

You don't have to use data-logging to use enhanced models. You can opt-in and get a discount if you do so. So, the enhanced model is indeed decoupled from data logging. Our documentation on [transcribing](https://cloud.google.com/speech-to-text/docs/phone-model#speech-select-model-python) using [enhanced ](https://cloud.google.com/speech-to-text/docs/enhanced-models#speech_transcribe_enhanced_model-python) models is consistent with this assertion.

Thank you for taking notice. We will correct the discrepancy on this repo sample feature description.

**Comment by tekkkon** [comment]
Thank you! @b-loved-dreamer
