### ISSUE TITLE
No response from client.recognize

### ISSUE THREAD

**Issue by sithu31296** [googleapis/python-speech#58]
I tried simple example from the documentation but I didn't get any response back from API. I traced the error and it gets stuck on `client.recognize` function. This happens only on my PC and other PC is fine. 

#### Environment details

  - OS type and version: Windows 10 
  - Python version: 3.7
  - pip version: 20.2.3

#### Code example

```python
import io
import os

# Imports the Google Cloud client library
from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types
from google.oauth2 import service_account

creds = service_account.Credentials.from_service_account_file('C:\\Users\\sithu\\Downloads\\speech-to-text-289906-3153d28585c3.json')

# Instantiates a client
client = speech.SpeechClient(credentials=creds)

# The name of the audio file to transcribe
file_name = os.path.join(
    os.path.dirname(__file__),
    'I am an expert.wav')

# Loads the audio into memory
with io.open(file_name, 'rb') as audio_file:
    content = audio_file.read()
    audio = types.RecognitionAudio(content=content)

config = types.RecognitionConfig(
    encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
    sample_rate_hertz=16000,
    language_code='en-US')

# Detects speech in the audio file
response = client.recognize(config, audio)

for result in response.results:
    print('Transcript: {}'.format(result.alternatives[0].transcript))
```
Thanks!

**Comment by b-loved-dreamer** [comment]
Hi @sithu31296 

I confirmed that this sample is working as expected. You stated that the issue is only showing in one of your machines but not the others. Please make sure you're following the [samples](https://cloud.google.com/speech-to-text/docs/quickstart-client-libraries).

**Comment by sithu31296** [comment]
@b-loved-dreamer Of course, I'm following the examples. I opened this issue because I don't know what is wrong. It won't show any error not even `RetryError` or `APICallError`. Anyway, thanks for the reply.
