### ISSUE TITLE
AttributeError: module 'google.cloud.speech' has no attribute 'RecognitionConfig'

### ISSUE THREAD

**Issue by alexandreraufast** [googleapis/python-speech#66]
I searched StackOverflow and Github.

#### Environment details
  - OS type and version: Linux Ubuntu 20.04
  - Python version: Python 3.8.2
  - pip version: pip 20.2.3
  - `google-cloud-speech` : Version: 1.3.2
Virtual Env and Pycharm

#### Steps to reproduce
  1. I used the code from [this page](https://github.com/googleapis/python-speech/blob/master/samples/microphone/transcribe_streaming_infinite.py).
  2. Pycharm makes this warning : `Cannot find reference 'RecognitionConfig' in 'speech.py' `
  3. When I run, I immediately got an error.

#### Stack trace
```
Traceback (most recent call last):
  File "/home/xxxxx/PycharmProjects/english_checker/main.py", line 271, in <module>
    main()
  File "/home/xxxxx/PycharmProjects/english_checker/main.py", line 216, in main
    config = speech.RecognitionConfig(
AttributeError: module 'google.cloud.speech' has no attribute 'RecognitionConfig'
```
####
I have all requirements (pyaudio, ...)

I don't understand what the missing part is about.

**Comment by b-loved-dreamer** [comment]
Hi @alexandreraufast 

One way to fix this issue is to include the imports:


> from google.cloud import speech
    from google.cloud.speech import enums
    from google.cloud.speech import types

And edit your configuration objects; like so:

>   config = types.RecognitionConfig(
        encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=SAMPLE_RATE,
        language_code="en-US",
        max_alternatives=1,
    )
    streaming_config = types.StreamingRecognitionConfig(
        config=config, interim_results=True
    )

And your request:

>  requests = (
      types.StreamingRecognizeRequest(audio_content=content)
      for content in audio_generator
     )

Give this a try.

**Comment by b-loved-dreamer** [comment]
Hi @alexandreraufast the sample has been updated to google-cloud-speech 2.0.0. The sample has been modified to support changes in the latest version of the API. Please let us know If you continue to experience issues.

**Comment by shashanke7y** [comment]
Hey @alexandreraufast, I also got this issue, I think that I got the same error, but I fixed by doing `$pip install --upgrade google-cloud-speech` like twice, because I am pretty sure that when you do the first time it install version 1 or something, then when you do it the second time it works. 

I hope it helps :)

**Comment by kasunvj** [comment]
> Hi @alexandreraufast
> 
> One way to fix this issue is to include the imports:
> 
> > from google.cloud import speech
> > from google.cloud.speech import enums
> > from google.cloud.speech import types
> 
> And edit your configuration objects; like so:
> 
> > config = types.RecognitionConfig(
> > encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
> > sample_rate_hertz=SAMPLE_RATE,
> > language_code="en-US",
> > max_alternatives=1,
> > )
> > streaming_config = types.StreamingRecognitionConfig(
> > config=config, interim_results=True
> > )
> 
> And your request:
> 
> > requests = (
> > types.StreamingRecognizeRequest(audio_content=content)
> > for content in audio_generator
> > )
> 
> Give this a try.

This worked for me. Thanks a lot

**Comment by TheAlchemist6** [comment]
I just had the same issue, nothing seems to fix it :(
