### ISSUE TITLE
AttributeError: 'datetime.timedelta' object has no attribute 'nanos'

### ISSUE THREAD

**Issue by dan-developer** [googleapis/python-speech#71]
The real time speech to text example has a bug:

```python
Traceback (most recent call last):
  File "C:/workspace/acessibility-tool/main.py", line 300, in <module>
    main()
  File "C:/workspace/acessibility-tool/main.py", line 283, in main
    listen_print_loop(responses, stream)
  File "C:/workspace/acessibility-tool/main.py", line 203, in listen_print_loop
    if result.result_end_time.nanos:
AttributeError: 'datetime.timedelta' object has no attribute 'nanos'
```

https://github.com/googleapis/python-speech/blob/master/samples/microphone/transcribe_streaming_infinite.py

**Comment by b-loved-dreamer** [comment]
Hi @dan-developer 

I ran `transcribe_streaming_infinite ` but did not get any timedelta errors referencing nanos. I, however, needed to update the imports section, the configuration and request object. Please take a look at this #66

**Comment by dan-developer** [comment]
Hello @b-loved-dreamer 

This is my configuration:

```python
client = speech.SpeechClient()
    config = speech.RecognitionConfig(
        encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=SAMPLE_RATE,
        language_code="en-US",
        max_alternatives=1,
    )
    streaming_config = speech.StreamingRecognitionConfig(
        config=config, interim_results=True
    )
```

Sometimes in the result fault the seconds or nanos:

alternatives {
  transcript: "days"
}
stability: 0.009999999776482582
result_end_time {
  nanos: 900000000
}

**Comment by daisukenagata** [comment]
Hello @b-loved-dreamer

my code

If it is speech.SpeechClient, an error will occur in 6,7,8 series versions.

```
    client = speech_v1.SpeechClient()
    config = speech_v1.RecognitionConfig(
        encoding=speech_v1.RecognitionConfig.AudioEncoding.LINEAR16,
        sample_rate_hertz=SAMPLE_RATE,
        language_code="ja-JP",
        max_alternatives=1,
    )
    streaming_config = speech_v1.StreamingRecognitionConfig(
        config=config, interim_results=True
    )
```

This is the result now.

```
  File "ResumableMicrophoneStream.py", line 294, in <module>
    main()
  File "ResumableMicrophoneStream.py", line 277, in main
    listen_print_loop(responses, stream)
  File "ResumableMicrophoneStream.py", line 197, in listen_print_loop
    if result.result_end_time.nanos:
AttributeError: 'datetime.timedelta' object has no attribute 'nanos'
```

**Comment by daisukenagata** [comment]
Hello @b-loved-dreamer
Hi @dan-developer

I fixed it for the time being.

```
        if result.result_end_time.seconds:
            result_seconds = result.result_end_time.seconds

        if result.result_end_time.seconds:
            result_seconds2 = result.result_end_time.seconds
        # if result.result_end_time.seconds:
        #     result_nanos = result.result_end_time.nanos

        stream.result_end_time = int((result_seconds * 1000) + (result_seconds2 / 1000000))
```

https://gist.github.com/daisukenagata/bc2a64de7fcf198d9b9d58fcbb767c69

**Comment by dan-developer** [comment]
Okay.

**Comment by b-loved-dreamer** [comment]
Hi @dan-developer, @daisukenagata the sample has been updated to google-cloud-speech 2.0.0. The sample has been modified to support changes in the latest version of the API. Please let us know If you continue to experience issues.

**Comment by eu42** [comment]
> nanos are no longer supported in google-cloud-speech 2.0.0 - the new API supports microseconds instead. We are updating the sample to reflect these changes.

Hi, @b-loved-dreamer, it would be nice if this can be mentioned in migration guide.
