### ISSUE TITLE
Wrong requirements in samples/*/requirements.txt

### ISSUE THREAD

**Issue by zub2** [googleapis/python-speech#79]
The `requirements.txt` in samples still specify version `google-cloud-speech==1.3.2`. But the code itself (at least in `python-speech/samples/microphone`) needs version 2.0.0.

As a result, when one blindly runs `pip install -r samples/microphone/requirements.txt` and then proceeds to run e.g. `samples/microphone/transcribe_streaming_mic.py`, the result is:
```
$ python samples/microphone/transcribe_streaming_mic.py 
Traceback (most recent call last):
  File "samples/microphone/transcribe_streaming_mic.py", line 197, in <module>
    main()
  File "samples/microphone/transcribe_streaming_mic.py", line 172, in main
    config = speech.RecognitionConfig(
AttributeError: module 'google.cloud.speech' has no attribute 'RecognitionConfig'
```
... which provides a suboptimal "getting started" experience.

#### Steps to reproduce

  1. `virtualenv testenv`
  1. `. testenv/bin/activate`
  1. `pip install -r samples/microphone/requirements.txt`
  1. `python samples/microphone/transcribe_streaming_mic.py`

The fix is to install `google-cloud-speech==2.0.0` instead of the old 1.3.2.

I think this issue is fixed in https://github.com/googleapis/python-speech/pull/78 but as it's not yet merged and others might run into this (and spend time figuring out what's wrong), I'm creating this issue.

**Comment by b-loved-dreamer** [comment]
Hi @zub2, thank you for making note of that. As you noted, we are going thorough the process of updating our samples to reflect the changes in 2.0.0.
