### ISSUE TITLE
speech_contexts results in type error: expected v1.SpeechContext, got SpeechContext

### ISSUE THREAD

**Issue by kpister** [googleapis/python-speech#82]
Please run down the following list and make sure you've tried the usual "quick fixes":

#### Environment details

  - OS type and version: MacOS Catalina
  - Python version: 3.8
  - pip version: 20.2.3
  - `google-cloud-speech` version: 2.0.0

#### Steps to reproduce

  1. Fill in the values needed and run code below

#### Code example

```python
from google.cloud import speech
client = speech.SpeechClient.from_service_account_json("keyfile_here")
config = {
        "language_code": "en-US",
        "encoding": speech.RecognitionConfig.AudioEncoding.LINEAR16,
        "speech_contexts": [speech.SpeechContext(phrases=["test", "two"])],
}
client.long_running_recognize(request={
       "config": config,
       "audio": speech.RecognitionAudio(uri="<URI_HERE>"),
}
```

Without the `speech_contexts` key, this is successful and doesn't encounter errors. But with `speech_contexts`, I get the error below.

#### Stack trace
```
  File "my_project/gcloud_stt.py", line 118, in transcribe_storage_uri
    response = _get_client().long_running_recognize(
  File ".../site-packages/google/cloud/speech_v1/services/speech/client.py", line 410, in long_running_recognize
    request = cloud_speech.LongRunningRecognizeRequest(request)
  File ".../site-packages/proto/message.py", line 416, in __init__
    pb_value = marshal.to_proto(pb_type, value)
  File ".../site-packages/proto/marshal/marshal.py", line 205, in to_proto
    pb_value = rule.to_proto(value)
  File ".../site-packages/proto/marshal/rules/message.py", line 32, in to_proto
    return self._descriptor(**value)
TypeError: Parameter to MergeFrom() must be instance of same class: expected google.cloud.speech.v1.SpeechContext got SpeechContext.
```

**Comment by b-loved-dreamer** [comment]
Hi @kpister, thank you for using our service. While looking at your code I noticed your ```config``` object is formatted in a way the service doesn’t like. You can update that to: 

```
config = speech.RecognitionConfig ( 
        sample_rate_hertz=16000,
        language_code="en-US",
         encoding=speech.RecognitionConfig.AudioEncoding.LINEAR16,
        speech_contexts=[speech.SpeechContext(phrases=["test", "two"])],)
```

Also, the ```long_running_recognize``` returns a ```operation```:
```
    operation = client.long_running_recognize( request = {
        "config": config,
        "audio": speech.RecognitionAudio(uri=storage_uri),
    }

    response = operation.result()
```

Please try this. It should work now.

**Comment by kpister** [comment]
Thank you, that indeed worked. 

Was it a part of the 2.0 migration that removed the old dictionary config approach? Why would it have been working as a dictionary when I didn't pass the `speech_contexts` key but fail when I did?

**Comment by b-loved-dreamer** [comment]
Hi @kpister, I am glad the solution worked for you. To answer your question: In 2.0.0 there have been substantial interface changes. This would implicitly explain the behavior you have experienced. Please refer to the [migration guide](https://github.com/googleapis/python-speech/blob/master/UPGRADING.md) for more details.
