### ISSUE TITLE
Avoiding high billing with infinite stream 

### ISSUE THREAD

**Issue by pauloesteban** [googleapis/python-speech#84]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Dear community,

I am seeing on my Console the billing tendency that Speech-To-Text API has a lot of usage when using infinite stream recognition. Is there a way to mitigate high costs for real-time transcription? The stream is open several hours a day but it's rarely used for the whole time. Will be VAD a practical solution?

Cheers,
Paulo

**Comment by b-loved-dreamer** [comment]
Hi @pauloesteban, thank you for posting your concern. Here are the [pricing factors](https://cloud.google.com/speech-to-text/pricing) for Speech-To-Text. One way to help mitigate the costs is to use [data logging](https://cloud.google.com/speech-to-text/docs/data-logging). A VAD sounds reasonable, but I'd say that depends on your specific implementation.

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if you have more questions.
