### ISSUE TITLE
Please update sample documentation to point to python-speech instead of python-docs-samples

### ISSUE THREAD

**Issue by ffeldhaus** [googleapis/python-speech#85]
As the code was moved from python-docs-samples to python-speech the documentation in the samples directory is not correct anymore. Please update all documentation (e.g. README) to point to the new git location. Currently the examples are not working as described.

**Comment by b-loved-dreamer** [comment]
Hi @ffeldhaus, thank you for taking notice of this. Can you please point to the samples you noticed are not working as described?

**Comment by ffeldhaus** [comment]
I noticed that the old repository is still mentioned in https://github.com/googleapis/python-speech/blob/master/samples/microphone/README.rst and https://github.com/googleapis/python-speech/blob/master/samples/snippets/README.rst

**Comment by b-loved-dreamer** [comment]
Thank you for pointing this out. We will take care of this. I will now close this issue. Please allow some time for us to make the necessary changes. If you still notice discrepancies after we make the changes or notice new ones, please reopen this issue or open a new one.
