### ISSUE TITLE
speec2srt.py is not working because of removal of submodules enums and types

### ISSUE THREAD

**Issue by hetul99** [googleapis/python-speech#86]
Following [this](https://www.youtube.com/watch?v=uBzp5xGSZ6o&ab_channel=GoogleCloudAPAC) for creating speech to srt using google apis. When running the command `python3 speech2srt.py --storage_uri gs://subtitlingsc/en.wav` is showing that 
```
File "speech2srt.py", line 19, in <module>
    from google.cloud.speech_v1 import enums
ImportError: cannot import name 'enums' from 'google.cloud.speech_v1'
```

I think this is due to removal of enums and types. Please do the needful and update those videos and [GitHub file](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/speech2srt/speech2srt.py)

**Comment by b-loved-dreamer** [comment]
Hi @hetul99, we're working on updating all references to the previous version of the client. Please take a look at this [issue](https://github.com/googleapis/python-speech/issues/79) for reference.

**Comment by b-loved-dreamer** [comment]
Thank you for your comments.
