### ISSUE TITLE
Speech: Docs section on model has broken HTML.

### ISSUE THREAD

**Issue by bbookman** [googleapis/python-speech#9]
The following is displayed on https://googleapis.github.io/google-cloud-python/latest/speech/gapic/v1/types.html#google.cloud.speech_v1.types.RecognitionConfig

model
Optional Which model to select for the given request. Select the model best suited to your domain to get best results. If a model is not explicitly specified, then we auto-select a model based on the parameters in the RecognitionConfig. .. raw:: html <table> .. raw:: html <tr> :: <td><b>Model</b></td> <td><b>Description</b></td> .. raw:: html </tr> .. raw:: html <tr> :: <td><code>command_and_search</code></td> <td>Best for short queries such as voice commands or voice search.</td> .. raw:: html </tr> .. raw:: html <tr> :: <td><code>phone_call</code></td> <td>Best for audio that originated from a phone call (typically recorded at an 8khz sampling rate).</td> .. raw:: html </tr> .. raw:: html <tr> :: <td><code>video</code></td> <td>Best for audio that originated from from video or includes multiple speakers. Ideally the audio is recorded at a 16khz or greater sampling rate. This is a premium model that costs more than the standard rate.</td> .. raw:: html </tr> .. raw:: html <tr> :: <td><code>default</code></td> <td>Best for audio that is not one of the specific audio models. For example, long-form audio. Ideally the audio is high-fidelity, recorded at a 16khz or greater sampling rate.</td> .. raw:: html </tr> .. raw:: html </table>

**Comment by meredithslota** [comment]
The linked issue was closed as a "Won't Fix" — @busunkim96 do you know what the right path here is instead?

**Comment by busunkim96** [comment]
@meredithslota I think the best solution would be to edit the comments in the .proto. This section uses raw HTML, which is banned by [AIP-192](https://aip.dev/192).

> Any formatting in comments must be in CommonMark. Headings and tables must not be used, as these cause problems for several tools, and are unsuitable for client library reference documentation.
> 
> Comments should use code font for property names and for literals (such as true).
>
> **Raw HTML must not be used.**

https://github.com/googleapis/googleapis/blob/a5d0708f0702f538fb069d89c0e92c5b14dca49e/google/cloud/speech/v1p1beta1/cloud_speech.proto#L343-L374
```proto
  // Which model to select for the given request. Select the model
  // best suited to your domain to get best results. If a model is not
  // explicitly specified, then we auto-select a model based on the parameters
  // in the RecognitionConfig.
  // <table>
  //   <tr>
  //     <td><b>Model</b></td>
  //     <td><b>Description</b></td>
  //   </tr>
  //   <tr>
  //     <td><code>command_and_search</code></td>
  //     <td>Best for short queries such as voice commands or voice search.</td>
  //   </tr>
  //   <tr>
  //     <td><code>phone_call</code></td>
  //     <td>Best for audio that originated from a phone call (typically
  //     recorded at an 8khz sampling rate).</td>
  //   </tr>
  //   <tr>
  //     <td><code>video</code></td>
  //     <td>Best for audio that originated from from video or includes multiple
  //         speakers. Ideally the audio is recorded at a 16khz or greater
  //         sampling rate. This is a premium model that costs more than the
  //         standard rate.</td>
  //   </tr>
  //   <tr>
  //     <td><code>default</code></td>
  //     <td>Best for audio that is not one of the specific audio models.
  //         For example, long-form audio. Ideally the audio is high-fidelity,
  //         recorded at a 16khz or greater sampling rate.</td>
  //   </tr>
  // </table>
  string model = 13;
```

**Comment by b-loved-dreamer** [comment]
I am closing this issue as it looks to have remained inactive for a long time. Feel free to reopen.
