### ISSUE TITLE
Question: long_running_recognize vs splitting the audio file

### ISSUE THREAD

**Issue by TaridaGeorge** [googleapis/python-speech#90]
Would long_running_recognize output better results while using the speaker diarization feature vs splitting the audio file in chunks of 15 seconds for example and sending them one by one to the recognizer? 

When is long_running_recognize preferred to be used?

**Comment by b-loved-dreamer** [comment]
Hi @TaridaGeorge, Speaker Diarization serves the purpose of enabling the recognition of multiple speakers in the same audio file, please see [here](https://cloud.google.com/speech-to-text/docs/multiple-voices) for more details. Speaker Diarization is used irrespective of wether you're making synchronous (```recognize```) or asynchronous (```long_running_recognize```) calls to the service. 

Splitting your audio data into smaller segments and sending them to the recognizer for processing sounds like a very specific use case for which I don't a definitive answer. 

```long_running_recognize``` is preferred to be used when transcribing long audio files (longer than 1 minute) to text using asynchronous speech recognition, [see here](https://cloud.google.com/speech-to-text/docs/async-recognize).

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.
