### ISSUE TITLE
Migration guide: error in example code

### ISSUE THREAD

**Issue by eu42** [googleapis/python-speech#98]
In the migration guide, there is following code snippet:

```python
from google.cloud import speech

client = speech.SpeechClient()

request = speech.RecognizeRequest(request={"config": config, "audio": audio})
response = client.list_voices(request=request)
```

If I don't miss something obvious, it should be as follows:

```python
from google.cloud import speech

client = speech.SpeechClient()

request = speech.RecognizeRequest(config=config, audio=audio)
response = client.recognize(request=request)
```

**Comment by b-loved-dreamer** [comment]
Hi @eu42, these are just variations in the way in which you can construct your request. These two are equivalent and will work as expected.

**Comment by b-loved-dreamer** [comment]
Closing this issue. Please reopen if needed.

**Comment by eu42** [comment]
As far as I know there is no method named `list_voices` for speech client. Also, `RecognizeRequest` does not take a request argument but `client` method does. I think what you meant is the availability of using either `request` argument or directly `config` and `audio` arguments for `recognize` method as two equivalent options.

So, for me this code snippet does not work with the following problems:
- `RecognizeRequest` does not take `request` argument
- `SpeechClient` has no method named `list_voices`

**Comment by b-loved-dreamer** [comment]
Hi @eu42, Thank you for pointing this out. I will check with our TW.
